name: cd

on:
  push:
    # tags:
    #   - 'v*'
    branches: [main]
      
permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install pyinstaller
          run: |
            python -m pip install --upgrade pip
            pip install pyinstaller
        
        - name: Compile
          run: pyinstaller ./src/main.py -w -F -n "PokiBooks"
        
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ github.ref_name }}
            release_name: Release ${{ github.ref_name }}
            body: |
              test

            draft: false
            prerelease: false
